# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - name: Configuration
    value: 'Release'
  - name: SolutionPath
    value: 'SampleSolution.sln'
  - name: DOTNET_ROLL_FORWARD
    value: 'Major'
  - name: _BuildConfig
    value: 'Debug'

# Only run against main
trigger:
  branches:
    include:
      - main
  paths:
    exclude:
    - /*.md

jobs:
- job: 'build_and_test'
  displayName: 'Build and Test'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore
      projects: '$(SolutionPath)'
      feedsToUse: config
      nugetConfigPath: NuGet.Config
      noCache: true

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build
      configuration: '$(Configuration)'
      projects: '$(SolutionPath)'
      arguments: '--no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet unit test'
    inputs:
      command: test
      configuration: $(Configuration)
      projects: |
        **/*.Tests.csproj
      arguments: '--no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=Coverage/'
      workingDirectory: '$(Build.SourcesDirectory)'
      publishTestResults: true

  - template: eng/azuredevops/pipelines/templates/CheckNugetStatus.yml
    parameters:
      sourcePath: '$(Build.SourcesDirectory)/src'
      nugetConfig: '$(Build.SourcesDirectory)/nuget.config'
      breakBuild: false

  - template: eng/azuredevops/pipelines/templates/CoverageResults.yml
    parameters:
      reports: $(Build.SourcesDirectory)/**/coverage.opencover.xml
      configuration: $(Configuration)
      condition: succeeded()
      assemblyfilters: '-xunit'
      breakBuild: false      

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'

- job: 'arcade_light_build'
  displayName: 'Build and Test (ArcadeLight)'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: NuGetAuthenticate@1
  - powershell: eng\commonlight\build.ps1
      -configuration $(_BuildConfig)
      -prepareMachine
      -ci
      -restore
      -test
      -projects $(Build.SourcesDirectory)\**\*Tests.csproj
      /bl:$(Build.SourcesDirectory)\artifacts\log\$(_BuildConfig)\test-windows.binlog
      /p:RestoreUsingNuGetTargets=false
    displayName: Run Tests
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

  - template: eng/azuredevops/pipelines/templates/CoverageResults.yml
    parameters:
      reports: $(Build.SourcesDirectory)/**/*.coverage.cobertura.xml
      configuration: $(Configuration)
      condition: succeeded()
      assemblyfilters: '-xunit'
      breakBuild: false      

- job: 'Static_Code_Analysis'
  displayName: 'Static code analysis'
  dependsOn: build_and_test
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    displayName: 'Use dotnet SDK (global)'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true

  - task: NuGetAuthenticate@1
    displayName: "Authenticate on nuget feeds"

  - task: DotNetCoreCLI@2
    displayName: "Restore dotnet Projects"
    inputs:
      command: restore
      projects: '$(SolutionPath)'
      feedsToUse: config
      nugetConfigPath: 'nuget.config'

  - template: eng/azuredevops/pipelines/templates/GenerateSBOM.yml
    parameters:
      projects: '$(SolutionPath)'
      outputPath: '$(Build.SourcesDirectory)\artifacts'
      publishSBOM: true
